apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/test/apps/composition
  prune: true
  postBuild:
    # Allows to template any nested kustomization
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
  patches:
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          value: "*"
      target:
        kind: HelmRelease
